name: Test schemas for each language

on:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  python-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schema:
          - pattern-escaped-slash-schema.json
          - pattern-unescaped-slash-schema.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python tests with matrix argument
        run: |
          python Python/test-pattern.py testdata.json ${{ matrix.schema }}

  rust-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schema:
          - pattern-escaped-slash-schema.json
          - pattern-unescaped-slash-schema.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          cargo fetch --manifest-path Rust/Cargo.toml

      - name: Run Rust tests
        run: |
          cargo run --manifest-path Rust/Cargo.toml testdata.json ${{ matrix.schema }}